### ISSUE TITLE
Feature: Custom Notification Messages

### ISSUE THREAD

**Issue by typomc** [Lenguita-AI/github-action-due-date-notifications-via-comments#11]
**Description:**
Allow users to customize the notification messages in the workflow file. Provide placeholders for dynamic content (e.g., `{daysUntilDue}`, `{dueDateStr}`) to give users flexibility in how the messages are formatted and presented.

**Feature Requirements:**
1. **User-Defined Messages:**
   - Allow users to specify custom messages for different scenarios (e.g., due date passed, due today, due in X days).
   - Include placeholders that can be replaced with dynamic content:
     - `{daysUntilDue}`: Number of days until the due date.
     - `{dueDateStr}`: The formatted due date string.

2. **Default Messages:**
   - Provide default messages for users who do not specify custom messages.

3. **Documentation:**
   - Update the documentation to include instructions on how to configure custom messages and the available placeholders.

**Example Configuration:**
In the workflow file, users should be able to specify custom messages like this:

```yaml
steps:
  - name: Notify Due Dates
    uses: user/repo@v1
    with:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      days-before-due: 3
      message-due-passed: "🚨 The due date for this issue has passed!"
      message-due-today: "⏰ This issue is due today!"
      message-due-soon: "📅 This issue is due in {daysUntilDue} day(s), on {dueDateStr}."
```

**Implementation Plan:**
1. **Modify Input Parameters:**
   - Add new input parameters for custom messages in the `action.yml` file.
   - Ensure that these parameters are optional and provide default values.

2. **Update Code:**
   - Update the main code to use custom messages if provided, or fall back to default messages.
   - Replace placeholders with actual values.

3. **Testing:**
   - Test with various configurations to ensure the feature works as expected.
   - Include edge cases where custom messages are not provided.

**Milestones:**
- [ ] Define new input parameters in `action.yml`.
- [ ] Update main logic to handle custom messages.
- [ ] Update documentation.
- [ ] Testing and validation.
